apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
    - name: emptydir-cr-1
      image: nginx
      volumeMounts:
        - name: emptydir-volume
          mountPath: /data
    - name: emptydir-cr-2
      image: busybox
      command: [ "sh", "-c", "echo Hello from Container 2 > /data/message.txt; sleep 3600" ]
      volumeMounts:
        - name: emptydir-volume
          mountPath: /data
  volumes:
    - name: emptydir-volume
      emptyDir: {}  