apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: sample-volume-mount-cr
    image: nginx:latest
    volumeMounts:
    - name: hostvolume
      mountPath: /cr_data
  volumes:
  - name: hostvolume
    hostPath:
      path: /data