apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set-simple
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [log-collection]}
  template:
    metadata:
      labels:
        app: log-collection
    spec:
      containers:
        - name: dms-lc-cr
          image: fluentd
          ports:
            - containerPort: 80
