apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-with-multi-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      environment: production
      zone: cluster
  template:
    metadata:
      labels:
        app: webapp
        environment: production
        zone: cluster
        tier: frontend
    spec:
      containers:
        - name: rs-with-ml-cr
          image: nginx:latest
          ports:
            - containerPort: 80
