apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-cs-namespace-level
  namespace: gowtham-ns
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
