apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:                      #RWO, RWM, ROO
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual         # optional
  hostPath:
    path: /data  # Replace with your desired host path
