apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: my-container
      image: nginx:latest
  tolerations:
    - key: example.com/no-schedule
      operator: "Exists"
      effect: "NoSchedule"
    - key: example.com/prefer-no-schedule
      operator: "Exists"
      effect: "PreferNoSchedule"
    - key: example.com/no-execute
      operator: "Exists"
      effect: "NoExecute"
