apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-for-custom-namespace
  namespace: gowtham-ns
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "0.5"
    defaultRequest:
      memory: "128Mi"
      cpu: "0.1"
    type: Container
