apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeport-deployment
  template:
    metadata:
      labels:
        app: nodeport-deployment
    spec:
      containers:
        - name: loadbalancer-container
          image: tutum/hello-world
          ports:
            - containerPort: 80
