apiVersion: v1
kind: Service
metadata:
  name: nodeport-deployment
spec:
  type: NodePort
  selector:
    app: nodeport-deployment
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30002
