apiVersion: v1
kind: Pod
metadata:
  name: pod-with-required-podaffinity
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - backend
          topologyKey: kubernetes.io/hostname
