apiVersion: v1
kind: Pod
metadata:
  name: preferred-node-affinity-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100  # Single weight preference
          preference:
            matchExpressions:
              - key: zone
                operator: In
                values:
                  - east
