apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: loadbalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

# no need to give nodeport in the load balancer 
# it will take automatic
