apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationcontroller-with-env
  labels:
    app: webapp
    environment: cluster
spec:
  replicas: 3
  selector:
    app: sample-rpc
  template:
    metadata:
      labels:
        app: sample-rpc
    spec:
      containers:
        - name: rpc-with-env-cr
          image: nginx:latest
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: db.example.com
            - name: DB_PORT
              value: "5432"
      volumes:
        - name: data-volume
          emptyDir: {}
      
