apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-image
      volumeMounts:
        - name: secret-volume
          mountPath: /path/to/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: example-secret
