apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-single-weight
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100  # Single weight preference
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - backend
