apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-double-weight
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 80
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - backend
        - weight: 20
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - frontend
