apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-with-single-expression
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: rs-with-sl-ex-cr
          image: nginx:latest
          ports:
            - containerPort: 80
