apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-pod-level
spec:
  containers:
    - name: rs-lm-pl-cr-1
      image: nginx:latest
    - name: rs-lm-pl-cr-2
      image: nginx:latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.5"
    limits:
      memory: "512Mi"
      cpu: "1"
