apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-pod-two-cr
spec:
  containers:
    - name: rs-lm-cr-1
      image: nginx:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "0.5"
        limits:
          memory: "512Mi"
          cpu: "1"
    - name: rs-lm-cr-2
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "0.3"
        limits:
          memory: "256Mi"
          cpu: "0.5"
