apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs # Replace with your provisioner
reclaimPolicy: Delete # This sets the reclaim policy for PVs created using this StorageClass

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  serviceName: example-service
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        storageClassName: standard
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
