apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-rollingupdate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dp-rlu
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dp-rlu
    spec:
      containers:
        - name: dp-with-rl-cr
          image: nginx:latest
          ports:
            - containerPort: 80
