apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env
spec:
  containers:
    - name: pod-env-cr
      image: nginx:latest
      env: 
        - name: nameoftheuser
          value: gowtham
        - name: degree
          value: m-tech
        - name: village
          value: thummalapalli
        - name: gmail
          value: gowthamreddy.6991@gmail.com
        - name: designation
          value: employee
        - name: specilazation
          value: powersystem
      ports:
        - containerPort: 80