apiVersion: v1
kind: Pod
metadata:
  name: mypod-with-restart
  labels:
    app: my-app
spec:
  restartPolicy: Always  # Change this to "OnFailure" or "Never" as needed
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
