apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-readyness
spec:
  containers:
    - name: liveness-readyness-cr
      image: nginx:latest
      ports:
        - containerPort: 80  
      livenessProbe:
        tcpSocket:
          port: 80        
        initialDelaySeconds: 10
        periodSeconds: 15
        timeoutSeconds: 5         # Set the timeout for the probe
        failureThreshold: 3       # Set the number of consecutive failures before pod restart
        successThreshold: 1       # Set the number of consecutive successes for the probe to be considered successful
      readinessProbe:
        tcpSocket:
          port: 80        
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1
      
