apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
type: Opaque
data:
  name: Z293dGhhbQ==        # gowtham
  village: dGh1bW1hbGFwYWxsaQ==  # thummalapalli

# in the containers the base64 values are automatically decoded